all: bonus1	bonusTrial bonusDeadlock bonus3

bonus1:
	gcc bonus1.c -o bonus1 -lpthread -lrt

bonusTrial:
	gcc bonusTrial.c -o bonusTrial -lpthread -lrt

bonusDeadlock:
	gcc bonusDeadlock.c -o bonusDeadlock -lpthread -lrt

bonus3:
	gcc bonus3.c -o bonus3 -lpthread -lrt
