all : Q1 Q2a Q2b Q2c_queue Q2c_stack Q3 Q5

Q1: 
	gcc Q1.c -o Q1


Q2a:
	gcc Q2a.c -o Q2a

Q2b:
	gcc Q2b.c -o Q2b

Q2c_queue:
	gcc Q2c_queue.c -o Q2c_queue

Q2c_stack:
	gcc Q2c_stack.c -o Q2c_stack

Q3:
	gcc Q3.c -o Q3

Q5:
	gcc Q5.c -o Q5


