all: sender reader

sender:
	gcc SenderMQ.c -o SenderMQ
	gcc SenderSocket.c -o SenderSocket
	gcc SenderFIFO.c -o SenderFIFO


reader:
	gcc ReaderMQ.c -o ReaderMQ
	gcc ReaderSocket.c -o ReaderSocket
	gcc ReaderFIFO.c -o ReaderFIFO

